version: '3.7'
services:
  backend:
    container_name: ${SERVICE_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
#      args:
#        GL_NPM_TOKEN:
    volumes:
      - .:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: yarn run start:dev
    env_file:
      - .env
    networks:
      - ${SERVICE_NETWORK_NAME}
    depends_on:
      - db
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:5.7@sha256:9415bfb9a83752d30b6395c84dde03573eeba7b5b9c937c0e09c3e7b32c76c93
    networks:
      - ${SERVICE_NETWORK_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mysql-db:/var/lib/mysql
networks:
  boilerplate-network:
volumes:
  mysql-db:
  nodemodules:
